# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: npm # See documentation for possible values
    directory: / # Location of package manifests
    schedule:
      interval: daily
    labels:
      - dependabot
    ignore:
    # 돈 새로 안내고 Wallaby 사용을 위해 업데이트 금지
      - dependency-name: vitest
      - dependency-name: vite
      - dependency-name: vite-node
