name: Auto Merge

on:
  pull_request_target:
    types:
      - labeled

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    if: "contains(github.event.pull_request.labels.*.name, 'mutation-completed')"
    steps:
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ secrets.TOKEN1 }}
          required-labels: mutation-completed
          do-not-merge-labels: never-merge

      - name: Remove mutation-completed Label
        if: always()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN1 }}
          script: |
            try {
              github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'mutation-completed'
              });
              console.log('Label mutation-completed removed successfully');
            } catch (error) {
              console.log('Error removing label or label not found:', error);
            }
