name: Auto-Merge Pull Request
# https://github.com/marketplace/actions/auto-merge-pull-request

on: push

# explicitly configure permissions, in case your GITHUB_TOKEN workflow permissions are set to read-only in repository settings
permissions:
  pull-requests: write # Necessary to comment on PRs
  issues: read # Necessary to read issue comments
  contents: write # Necessary to merge PRs

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: "contains(github.event.pull_request.labels.*.name, 'mutation-completed')"
    steps:
      - uses: reitermarkus/automerge@v2.8.0
        with:
          token: ${{ secrets.TOKEN1 }}
          merge-method: merge
          do-not-merge-labels: never-merge
          required-labels: |
            automated
            ready-to-merge
          pull-request: ${{ github.event.inputs.pull-request }}
          review: ${{ github.event.inputs.review }}
