name: Auto Merge

on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ secrets.TOKEN1 }}
          required-labels: mutation-completed
          do-not-merge-labels: never-merge
