name: Build and Tests

on: push

# explicitly configure permissions, in case your GITHUB_TOKEN workflow permissions are set to read-only in repository settings
permissions:
  pull-requests: write # Necessary to comment on PRs
  issues: read # Necessary to read issue comments
  contents: read # Necessary to access the repo content

jobs:
  build:
    name: Build and Tests
    timeout-minutes: 15
    runs-on: ubuntu-latest
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    # env:
    #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    #  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 23.5.0

      - name: Install pnpm
        run: npm install -g pnpm@9.15.4

      - name: Verify pnpm installation
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm run playwright-install-env

      - name: Test
        run: pnpm run test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-reports
          path: '**/playwright-report/'
          retention-days: 30
