name: Build & Tests

on:
  pull_request:
    types:
      - labeled

# explicitly configure permissions, in case your GITHUB_TOKEN workflow permissions are set to read-only in repository settings
permissions:
  pull-requests: write # Necessary to comment on PRs
  issues: read # Necessary to read issue commentsds
  contents: read # Necessary to access the repo content

jobs:
  build:
    name: Build & Tests
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    if: "contains(github.event.pull_request.labels.*.name, 'mutation-completed')"

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # 월간 캐시 순환 키 생성
      - name: Generate cache rotation keys
        id: cache-rotation
        shell: bash
        run: |
          echo "YEAR_MONTH=$(/bin/date -u "+%Y%m")" >> $GITHUB_OUTPUT

      # turbo 캐시 최적화 - package.json 해시 기반으로 변경
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: |
            .turbo
            node_modules/.cache/turbo
          key: ${{ runner.os }}-turbo-${{ steps.cache-rotation.outputs.YEAR_MONTH }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ steps.cache-rotation.outputs.YEAR_MONTH }}-
            ${{ runner.os }}-turbo-

      # pnpm 설치 (packageManager 버전과 일치)
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.4.1
          run_install: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 23.5.0
          cache: pnpm

      # 최적화된 설치 명령
      - name: Install dependencies
        run: pnpm install --prefer-offline

      - name: Install Playwright Browsers
        run: pnpm run playwright-install-env

      - name: Test
        run: pnpm run test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-reports
          path: '**/playwright-report/'
          retention-days: 30
