name: Check Secrets

on:
  workflow_call: {}

permissions:
  pull-requests: write # Necessary to comment on PRs
  issues: read # Necessary to read issue commentsds
  contents: read # Necessary to access the repo content

jobs:
  check-secrets:
    name: Check Secrets
    runs-on: ubuntu-latest

    steps:
      # 기본 checkout 사용 (pull_request 이벤트는 base commit을 checkout)
      - name: Checkout code
        uses: actions/checkout@v4

      # 비밀 스캔 (이제 PR 변경사항만 스캔)
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          # PR의 base 및 head 커밋 SHA를 명시적으로 전달
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }}
          extra_args: --results=verified,unknown
