name: Check & Lint

on:
  pull_request_target:
    types:
      - labeled
      - synchronize

permissions:
  pull-requests: write # Necessary to comment on PRs
  issues: read # Necessary to read issue comments
  contents: read # Necessary to access the repo content

jobs:
  check-lint:
    name: Check & Lint
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    if: github.event.action == 'labeled' && github.event.label.name == 'mutation-finished'

    steps:
      # 저장소 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          token: ${{ secrets.TOKEN1 }}

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      # pnpm 설치 (packageManager 버전과 일치)
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      # Node.js 환경 설정 (package.json의 engines.node 버전과 일치)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm

      # 의존성 설치 최적화
      - name: Install dependencies
        run: pnpm install --prefer-offline

      - name: paraglide-compile
        run: pnpm --filter=@library/paraglide exec node ./src/compile.js

      # 린트 실행
      - name: Run Lint
        run: pnpm run lint
