name: Check Secrets

on:
  pull_request_target:
    types:
      - labeled
      - synchronize

permissions:
  pull-requests: write # Necessary to comment on PRs
  issues: read # Necessary to read issue commentsds
  contents: read # Necessary to access the repo content

jobs:
  check-secrets:
    name: Check Secrets
    runs-on: ubuntu-latest
    if: |
      (github.event.action == 'labeled' && github.event.label.name == 'mutation-finished') ||
      (github.event.action == 'synchronize' && contains(github.event.head_commit.message, '[automated-mutation]'))

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown
