name: Lint fix & Format

on: pull_request_target

# explicitly configure permissions, in case your GITHUB_TOKEN workflow permissions are set to read-only in repository settings
permissions:
  pull-requests: write # Necessary to comment on PRs
  issues: read # Necessary to read issue comments
  contents: write

jobs:
  build:
    name: Lint fix & Format
    timeout-minutes: 15
    runs-on: ubuntu-latest
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    # env:
    #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    #  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      # 저장소 코드 체크아웃
      - uses: actions/checkout@v4
        with:
          # Checkout the fork/head-repository and push changes to the fork.
          # If you skip this, the base repository will be checked out and changes
          # will be committed to the base repository!
          repository: ${{ github.event.pull_request.head.repo.full_name }}

          # Checkout the branch made in the fork. Will automatically push changes
          # back to this branch.
          ref: ${{ github.head_ref }}

      # Node.js 환경 설정 (package.json의 engines.node 버전과 일치)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.5.0
      # Corepack 활성화 (packageManager 버전 자동 감지)
      - name: Enable Corepack
        run: corepack enable
      # pnpm 설치 (packageManager 버전과 일치)
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.4.1
      # 의존성 설치
      - name: Install dependencies
        run: pnpm install

      # 린트 실행
      - name: Run Lint & Format
        run: pnpm run lint-fix

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Lint & Format
