name: Main Orchestrator

on:
  pull_request:
    types:
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

# explicitly configure permissions, in case your GITHUB_TOKEN workflow permissions are set to read-only in repository settings
permissions:
  pull-requests: write # Necessary to comment on PRs
  issues: read # Necessary to read issue commentsds
  contents: write
  checks: write
  actions: read

jobs:
  check-secrets:
    name: Check Secrets
    if: github.event.action == 'labeled' && github.event.label.name == 'mutation-finished'
    uses: ./.github/workflows/check-secrets.yml
    secrets: inherit

  link-check:
    name: Link Check
    if: github.event.action == 'labeled' && github.event.label.name == 'mutation-finished'
    uses: ./.github/workflows/link-check.yml
    secrets: inherit

  ninja-i18n:
    name: Ninja i18n Action
    if: github.event.action == 'labeled' && github.event.label.name == 'mutation-finished'
    uses: ./.github/workflows/ninja-i18n.yml
    secrets: inherit

  check-lint:
    name: Check & Lint
    needs: [check-secrets, link-check, ninja-i18n]
    uses: ./.github/workflows/check-lint.yml
    secrets: inherit

  build-tests:
    name: Build & Tests
    needs: [check-secrets, link-check, ninja-i18n]
    uses: ./.github/workflows/build-tests.yml
    secrets: inherit

  deploy:
    name: Deploy
    needs: [check-lint, build-tests]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      called_by_main: true
