name: After Push Hook
on:
  pull_request:
    types: [synchronize]

jobs:
  comment:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: /gemini review
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.TOKEN1}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '/gemini review'
            })