name: Sentry

on:
  pull_request_target:
    types:
      - labeled

# explicitly configure permissions, in case your GITHUB_TOKEN workflow permissions are set to read-only in repository settings
permissions:
  pull-requests: write # Necessary to comment on PRs
  issues: read # Necessary to read issue commentsds
  contents: read # Necessary to access the repo content

jobs:
  build:
    name: Sentry
    runs-on: ubuntu-latest
    if: github.event.action == 'labeled' && github.event.label.name == 'mutation-finished'

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Install dotenvx
        run: curl -sfS https://dotenvx.sh/install.sh | sh

      - name: Load environment variables
        run: dotenvx run -f .env.private -f .env.public -- bash -lc 'env >> "$GITHUB_ENV"'
        env:
          DOTENV_PRIVATE_KEY_PRIVATE: ${{ secrets.DOTENV_PRIVATE_KEY_PRIVATE }}

      - name: Create Sentry release
        uses: getsentry/action-release@v3
        with:
          environment: production
